### ISSUE TITLE
API key should never be hardcoded since It is available to everyone viewing your project

### ISSUE THREAD

**Issue by Chetan-Goyal** [lambiengcode/binance_ui#1]
https://github.com/hongvinhmobile/binance_ui/blob/1597200e6b6a0762b17b18f940c18b41bca4e4df/lib/src/pages/home/home_page.dart#L20

You can use env variables or store them separately in a file that could be added in gitignore.

**Comment by lambiengcode** [comment]
Tks bro! I'll remove value and comment below variable.

**Comment by Chetan-Goyal** [comment]
No Problem. The source code of your project looks well organized. If possible, add some pictures of the UI also. It will help me and some other visitors to see your work before going through the source code.
